
include ../config.mk

all:

strip:

install:
	mkdir -p $(DESTDIR)$(mandir)/man6
	$(INSTALL_DATA) gtkballs.6x $(DESTDIR)$(mandir)/man6

install-strip: install

uninstall:
	rm -f $(DESTDIR)$(mandir)/man6/gtkballs.6x


clean:

distclean:


