
include ../config.mk

all:

strip:

install:
	mkdir -p $(DESTDIR)$(datadir)/gtkballs
	cp -fv *.png $(DESTDIR)$(datadir)/gtkballs
	cp -rfv themes $(DESTDIR)$(datadir)/gtkballs

install-strip: install

uninstall:
	rm -rfv mkdir -p $(DESTDIR)$(datadir)/gtkballs

clean:

distclean:


